### ISSUE TITLE
Fails to generate module

### ISSUE THREAD

**Issue by MartinElvar** [ahamez/protox#3]
I have the following protobuf, which protox seems to compile fine.

```
message CSVCMsg_SendTable {
	message sendprop_t {
		optional int32 type = 1;
		optional string var_name = 2;
		optional int32 flags = 3;
		optional int32 priority = 4;
		optional string dt_name = 5;
		optional int32 num_elements = 6;
		optional float low_value = 7;
		optional float high_value = 8;
		optional int32 num_bits = 9;
	}

	optional bool is_end = 1;
	optional string net_table_name = 2;
	optional bool needs_decoder = 3;
	repeated .CSVCMsg_SendTable.sendprop_t props = 4;
}
```

I then want to decode my binary using `CSVCMsg_SendTable.decode!(message)`, but i get the following error.

```
** (UndefinedFunctionError) function CSVCMsg_SendTable.SendpropT.get_required_fields/0 is undefined (module CSVCMsg_SendTable.SendpropT is not available)
    CSVCMsg_SendTable.SendpropT.get_required_fields()
    (protox) lib/protox/decode.ex:149: Protox.Decode.parse_delimited/2
    (protox) lib/protox/decode.ex:85: Protox.Decode.parse_value/3
    (protox) lib/protox/decode.ex:64: Protox.Decode.parse_key_value/4
    (protox) lib/protox/decode.ex:17: Protox.Decode.decode!/3
    (demex) lib/demex.ex:160: Demex.parse_data_table/1
    (demex) lib/demex.ex:146: Demex.process_data_tables/1
    (demex) lib/demex.ex:89: Demex.process_bin/1
```

Without deeper knowledge of how the parser works, should protox generate the missing module? Or am i missing something? 

Thank you.

**Comment by ahamez** [comment]
OK, I still have to narrow down the exact problem. But in the meantime, there's a quick fix you can apply on your side: just rename `sendprop_t` into `SendpropT` in the proto file. The serialization won't be affected.
